version: '3.7.4'
services:
  app:
    build: ./app/
    depends_on:
      - db
    networks:
      - mynet
    environment:
      PYTHONUNBUFFERED: 1

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "zno_db"
      POSTGRES_HOST: "db"
    ports:
      - '5432:5432'
    networks:
      - mynet

  migrate:
    build: ./app/
    depends_on:
      - db
    environment:
      PYTHONUNBUFFERED: 1
      FLASK_APP: "app.py"
      FLASK_ENV: "development"
    command: "flask db upgrade"
    networks:
      - mynet

networks:
  mynet: