version: '3.7.4'
services:
  app:
    build:
      context: ./app/
      dockerfile: Dockerfile.app
    depends_on:
      - db
    networks:
      - mynet
    environment:
      PYTHONUNBUFFERED: 1

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "zno_db"
      POSTGRES_HOST: "db"
    ports:
      - '5432:5432'
    networks:
      - mynet

  migrate:
    build:
      context: ./app/
      dockerfile: Dockerfile.app
    depends_on:
      - db
    environment:
      PYTHONUNBUFFERED: 1
      FLASK_APP: "app.py"
      FLASK_ENV: "development"
    command: "flask db upgrade"
    networks:
      - mynet

  web:
    build:
      context: ./app/
      dockerfile: Dockerfile.web
    depends_on:
      - db
    environment:
      PYTHONUNBUFFERED: 1
      FLASK_APP: "front.py"
      FLASK_ENV: "development"
    ports:
      - '5000:5000'
    networks:
      - mynet

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - mynet

networks:
  mynet: